#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

namespace scyllagpt {

enum class ContentView {
    Editor,
    Settings,
    Access,
    Diagnostics,
    Shortcuts,
    GettingStarted,
    Keyring,
};

enum class SettingsSection {
    Providers,
    Editor,
    Terminal,
    Knowledge,
    Mcp,
    Strata,
    Security,
    Advanced,
};

// Settings → Security horizontal subpages (Slice A hierarchy).
enum class SecuritySubpage {
    Overview,
    Keyring,
    Environments,
    Connections,
    Policy,
};

// Shared command / control IDs (menu, accelerators, toolbar, center-pane).
enum CmdId : int {
    Cmd_SignIn = 1001,
    Cmd_SignOut,
    Cmd_NewChat,
    Cmd_Send,
    Cmd_Stop,
    Cmd_Settings,
    Cmd_OpenFolder,
    Cmd_OpenFile,
    Cmd_CloseTab,
    Cmd_Goto,
    Cmd_Replace,
    Cmd_FocusComposer,
    Cmd_ToggleFiles,
    Cmd_ToggleHistory,
    Cmd_FocusEditor,
    Cmd_TabEditor,
    Cmd_TabAgent,
    Cmd_Models,
    Cmd_Transcript,
    Cmd_Composer,
    Cmd_Status,
    Cmd_Account,
    Cmd_HomeHint,
    Cmd_Threads,
    Cmd_Tree,
    Cmd_Filter,
    Cmd_Search,
    Cmd_Editor,
    Cmd_EditorStatus,
    Cmd_HdrFiles,
    Cmd_HdrEditor,
    Cmd_HdrAgent,
    Cmd_HdrHistory,
    Cmd_Project,
    Cmd_AgentHint,
    Cmd_Tabs,
    Cmd_Find,
    Cmd_ToggleFind,
    Cmd_Save,
    Cmd_Scope,
    Cmd_Ctx,
    Cmd_AddFile,
    Cmd_AddSel,
    Cmd_CodexExe = 2001,
    Cmd_PinChat,
    Cmd_ArchiveChat,
    Cmd_RenameChat,
    Cmd_ChatTabs,
    Cmd_RemoveCtx,
    Cmd_RefreshFiles,
    Cmd_CopyRuntime,
    Cmd_EmptyOpenFile,
    Cmd_EmptyOpenFolder,
    Cmd_Exit = 2100,
    Cmd_EditUndo,
    Cmd_EditRedo,
    Cmd_EditCut,
    Cmd_EditCopy,
    Cmd_EditPaste,
    Cmd_EditSelectAll,
    Cmd_ViewWrap,
    Cmd_ViewWhitespace,
    Cmd_ToggleTerminal,
    Cmd_NewTerminal,
    Cmd_ClearCtx,
    Cmd_AccessShow,
    Cmd_AccessFolders,
    Cmd_AccessKeyring,
    Cmd_HelpAbout,
    Cmd_HelpShortcuts,
    Cmd_HelpDiag,
    Cmd_AiProviders,
    Cmd_PermInfo,
    Cmd_HelpGettingStarted,
    Cmd_ContentBack = 2300,
    Cmd_ContentNav,
    Cmd_ContentBody,
    Cmd_SetOaStatus,
    Cmd_SetOaSignIn,
    Cmd_SetOaSignOut,
    Cmd_SetClStatus,
    Cmd_SetClKey,
    Cmd_SetClCode,
    Cmd_SetClDisc,
    Cmd_SetDefLabel,
    Cmd_SetDefCombo,
    Cmd_SetCodex,
    Cmd_SetCopyRuntime,
    Cmd_SetWrap,
    Cmd_SetWhitespace,
    Cmd_SetEnterSends,
    Cmd_GsOpenFolder,
    Cmd_GsProviders,
    Cmd_Terminal,
    Cmd_PanelShowProblems,
    Cmd_PanelShowOutput,
    Cmd_PanelShowPorts,

    // Settings → MCP (2600+; Knowledge Settings uses 2401–2418, Terminal 2500+)
    Cmd_McpList = 2600,
    Cmd_McpDetail,
    Cmd_McpAdd,
    Cmd_McpAddAccount,
    Cmd_McpManage,
    Cmd_McpReauth,
    Cmd_McpCheck,
    Cmd_McpDisable,
    Cmd_McpDisconnect,
    Cmd_McpRemove,
    Cmd_McpAddTemplate,
    Cmd_McpAddName,
    Cmd_McpAddAlias,
    Cmd_McpAddEndpoint,
    Cmd_McpAddSave,
    Cmd_McpAddCancel,
    Cmd_McpAliasPopup,
    // Add-form transport picker + browse-mode probe (2617, 2618).
    Cmd_McpAddTransport,
    Cmd_McpTest,
    // Manage (edit) form (2619+). Stays below the Security block at 2800.
    Cmd_McpEditName,
    Cmd_McpEditAlias,
    Cmd_McpEditTransport,
    Cmd_McpEditEndpoint,
    Cmd_McpEditEnabled,
    Cmd_McpEditScopeAll,
    Cmd_McpEditScopeList,
    Cmd_McpEditSave,
    Cmd_McpEditCancel,

    // Settings → Terminal (2500+)
    Cmd_SetTermProfiles = 2500,
    Cmd_SetTermDefault,
    Cmd_SetTermPolicy,
    Cmd_SetTermRefresh,
    Cmd_SetTermCustomName,
    Cmd_SetTermCustomExe,
    Cmd_SetTermCustomBrowse,
    Cmd_SetTermCustomArgs,
    Cmd_SetTermAddCustom,
    Cmd_SetTermToggleEnable,
    Cmd_SetTermCwdMode,
    Cmd_SetTermCwdPath,
    Cmd_SetTermCwdBrowse,
    Cmd_SetTermEditCustom,
    Cmd_SetTermDupCustom,
    Cmd_SetTermCancelEdit,

    // Settings → Security sub-tabs (2800+)
    Cmd_SecTabOverview = 2800,
    Cmd_SecTabKeyring,
    Cmd_SecTabEnvironments,

    // Security Overview
    Cmd_SecOvKeyringStatus,
    Cmd_SecOvKeyringPrimary,   // Create / Unlock / Lock context
    Cmd_SecOvKeyringManage,
    Cmd_SecOvProjectStatus,
    Cmd_SecOvManageEnv,
    Cmd_SecOvManageSecrets,
    Cmd_SecOvPolicyStatus,
    Cmd_SecOvManagePolicy,

    // Project Environments (rewritten)
    Cmd_EnvTitle,
    Cmd_EnvDesc,
    Cmd_EnvProject,
    Cmd_EnvActiveLbl,
    Cmd_EnvActive,
    Cmd_EnvList,
    Cmd_EnvAdd,
    Cmd_EnvManage,
    Cmd_EnvSetActive,
    Cmd_EnvDup,
    Cmd_EnvDelete,
    Cmd_EnvBack,
    Cmd_EnvDetailName,
    Cmd_EnvInheritLbl,
    Cmd_EnvInherit,
    Cmd_EnvVars,
    Cmd_EnvAddVar,
    Cmd_EnvEditVar,
    Cmd_EnvRemoveVar,
    Cmd_EnvDetailDup,
    Cmd_EnvDetailDelete,
    Cmd_EnvAddEnvName,
    Cmd_EnvAddEnvInherit,
    Cmd_EnvAddEnvSave,
    Cmd_EnvAddEnvCancel,
    Cmd_EnvVarFormName,
    Cmd_EnvVarPlain,
    Cmd_EnvVarProtected,
    Cmd_EnvVarValue,
    Cmd_EnvVarSecret,
    Cmd_EnvVarUnlock,
    Cmd_EnvVarAvailHuman,
    Cmd_EnvVarAvailAgent,
    Cmd_EnvVarAvailRecipes,
    Cmd_EnvVarSave,
    Cmd_EnvVarCancel,

    // Settings → Security → Execution Policy
    Cmd_SecTabPolicy,
    Cmd_SecPolStatus,
    Cmd_SecPolHumanLbl,
    Cmd_SecPolHuman,
    Cmd_SecPolHumanHint,
    Cmd_SecPolAgentLbl,
    Cmd_SecPolAgent,
    Cmd_SecPolAgentHint,
    Cmd_SecPolRecipesLbl,
    Cmd_SecPolRecipes,
    Cmd_SecPolRecipesHint,
    Cmd_SecPolStrict,
    Cmd_SecPolReset,

    // Status bar segments
    Cmd_StatusEnv,

    // Project tree context menu (project root)
    Cmd_TreeProjectEnv,
    Cmd_TreeProjectSecrets,
    Cmd_TreeProjectSecurity,

    // Settings → Advanced / UI Gallery
    Cmd_UiGallery = 3900,

    // Settings → Agent Providers (card UI)
    Cmd_ProvOaManage = 3950,
    Cmd_ProvOaRefresh,
    Cmd_ProvOaDefault,
    Cmd_ProvOaSearch,
    Cmd_ProvOaModels,
    Cmd_ProvOaEnableAll,
    Cmd_ProvOaDisableAll,
    Cmd_ProvOaDefaultFooter,
    Cmd_ProvClManage,
    Cmd_ProvClRefresh,
    Cmd_ProvClDefault,
    Cmd_ProvClSearch,
    Cmd_ProvClModels,
    Cmd_ProvClEnableAll,
    Cmd_ProvClDisableAll,
    Cmd_ProvClDefaultFooter,
    Cmd_ProvCurConnect,
    Cmd_ProvCurLearn,
    Cmd_ProvActiveProvider,
    Cmd_ProvActiveModel,
    // OpenAI API (BYOK)
    Cmd_ProvOaApiManage,
    Cmd_ProvOaApiRefresh,
    Cmd_ProvOaApiDefault,
    Cmd_ProvOaApiSearch,
    Cmd_ProvOaApiModels,
    Cmd_ProvOaApiEnableAll,
    Cmd_ProvOaApiDisableAll,
    Cmd_ProvOaApiDefaultFooter,
    Cmd_ProvOaApiConnect,
    Cmd_ProvOaApiDisc,
    // Claude API (BYOK)
    Cmd_ProvClApiManage,
    Cmd_ProvClApiRefresh,
    Cmd_ProvClApiDefault,
    Cmd_ProvClApiSearch,
    Cmd_ProvClApiModels,
    Cmd_ProvClApiEnableAll,
    Cmd_ProvClApiDisableAll,
    Cmd_ProvClApiDefaultFooter,
    Cmd_ProvClApiConnect,
    Cmd_ProvClApiDisc,

    // Settings → Security → Connections. Explicitly based and contiguous so the page can claim the
    // whole block with one range test, the way the Environments page does.
    Cmd_ConnFirst = 4100,
    Cmd_ConnTitle = Cmd_ConnFirst,
    Cmd_ConnDesc,
    Cmd_ConnProject,
    Cmd_ConnList,
    Cmd_ConnAdd,
    Cmd_ConnManage,
    Cmd_ConnDup,
    Cmd_ConnDelete,
    Cmd_ConnToggleEnabled,

    // Detail chrome
    Cmd_ConnBack,
    Cmd_ConnDetailTitle,
    Cmd_ConnStatus,
    Cmd_ConnSecRoute,
    Cmd_ConnSecCreds,
    Cmd_ConnSecPolicy,
    Cmd_ConnSave,
    Cmd_ConnCancel,
    Cmd_ConnTest,
    Cmd_ConnUnlock,

    // Route section
    Cmd_ConnName,
    Cmd_ConnAlias,
    Cmd_ConnEnabled,
    Cmd_ConnRoute,
    Cmd_ConnSshHost,
    Cmd_ConnSshHostRef,
    Cmd_ConnSshPort,
    Cmd_ConnSshPortRef,
    Cmd_ConnSshUser,
    Cmd_ConnSshUserRef,

    // Credentials section
    Cmd_ConnKeyRef,
    Cmd_ConnPassphraseRef,
    Cmd_ConnAuthRef,
    Cmd_ConnHostKey,
    Cmd_ConnEngine,
    Cmd_ConnDbHost,
    Cmd_ConnDbHostRef,
    Cmd_ConnDbPort,
    Cmd_ConnDbPortRef,
    Cmd_ConnDbName,
    Cmd_ConnDbUserRef,
    Cmd_ConnDbPassRef,
    Cmd_ConnTlsRef,

    // Policy section
    Cmd_ConnPolRead,
    Cmd_ConnPolData,
    Cmd_ConnPolSchema,
    Cmd_ConnPolAdmin,
    Cmd_ConnPolUnrestricted,
    Cmd_ConnPolMultiStatement,
    Cmd_ConnResVisibility,
    Cmd_ConnResMaxRows,
    Cmd_ConnResMaxBytes,
    Cmd_ConnResTimeout,
    Cmd_ConnResMaxText,
    Cmd_ConnResBinary,
    Cmd_ConnLast = Cmd_ConnResBinary,

    // Security subpage tab
    Cmd_SecTabConnections,
};

struct CommandUiState {
    bool has_dirty_doc = false;
    bool has_active_doc = false;
    bool generating = false;
    bool word_wrap = false;
    bool show_whitespace = false;
    bool files_visible = false;
    bool history_visible = false;
    bool focus_editor = false;
    bool terminal_visible = false;
    bool has_selection_context = false;
    bool has_context_chips = false;
};

void menu_apply_command_state(HMENU popup, const CommandUiState& st);

const wchar_t* content_view_title(ContentView view);
const wchar_t* settings_section_label(SettingsSection section);

}  // namespace scyllagpt
