#include "scyllagpt/terminal_screen.h"
#include "scyllagpt/terminal_session.h"
#include <iostream>

int run_terminal_screen_tests() {
    int failures = 0;
    auto check = [&](bool ok, const char* label) { if (!ok) { ++failures; std::cerr << "terminal: " << label << '\n'; } };
    using scyllagpt::TerminalScreen;
    TerminalScreen screen;
    screen.feed("prompt> abc\b \b");
    check(screen.text() == L"prompt> ab", "backspace redraw erases exactly one cell");
    screen.feed("\r\x1b[8C\x1b[Kxy");
    check(screen.text() == L"prompt> xy", "cursor right and erase preserve prompt");
    screen.feed("\r\nnext\r\n");
    check(screen.text() == L"prompt> xy\rnext\r", "CRLF preserves prior lines");
    const std::string transcript = "\x1b[2J\x1b[Hprompt> abc\r\x1b[10C\x1b[K\x1b]0;title\x1b\\\r\n\xc3\xa9\xf0\x9f\x98\x80";
    TerminalScreen whole; whole.feed(transcript);
    for (std::size_t i = 0; i <= transcript.size(); ++i) {
        TerminalScreen split; split.feed(std::string_view(transcript).substr(0, i)); split.feed(std::string_view(transcript).substr(i));
        check(split.text() == whole.text(), "every possible read boundary gives same screen");
    }
    TerminalScreen bytes; for (char c : transcript) bytes.feed(std::string_view(&c, 1));
    check(bytes.text() == whole.text(), "single byte reads including UTF-8 and OSC terminator");
    TerminalScreen clear;
    clear.feed("one\r\ntwo\x1b[1;2H\x1b[0J");
    check(clear.text() == L"o", "ED0 clears from cursor without clearing preceding text");
    TerminalScreen middle; middle.feed("abcd\x1b[2DXY");
    check(middle.text() == L"abXY", "cursor left overwrites in place");
    middle.feed("\x1b[2D\x1b[P");
    check(middle.text() == L"abY", "delete at cursor");
    middle.feed("\x1b[6n"); check(middle.take_reply() == "\x1b[1;3R", "cursor position report");
    TerminalScreen wrap; wrap.resize(4, 2); wrap.feed("abcdX\r\nY");
    check(wrap.text() == L"abcd\rX\rY", "delayed wrap and bounded viewport scrollback");
    wrap.resize(8, 1); check(wrap.text() == L"abcd\rX\rY", "shrinking preserves visible cursor line");
    TerminalScreen alternate; alternate.feed("shell\x1b[?1049hfull screen\x1b[?1049l");
    check(alternate.text() == L"shell", "alternate screen restores shell");

    // Real ConPTY + hidden child: validate keyboard bytes, display, process teardown,
    // and visibility after output arrives while dismissed. No interactive app is opened.
    HWND parent = CreateWindowExW(0, L"STATIC", L"Terminal tests", WS_POPUP, 0, 0, 640, 320,
                                  nullptr, nullptr, GetModuleHandleW(nullptr), nullptr);
    check(parent != nullptr, "hidden test parent");
    if (parent) {
        scyllagpt::TerminalSessionManager manager;
        scyllagpt::TerminalProfile profile;
        wchar_t system[MAX_PATH]{}; GetSystemDirectoryW(system, MAX_PATH);
        profile.executable = std::wstring(system) + L"\\cmd.exe";
        profile.args = L"/D /Q";
        profile.name = L"cmd test";
        scyllagpt::TerminalCreateOpts opts;
        std::wstring error;
        check(manager.create_session(parent, parent, GetModuleHandleW(nullptr), 100, profile, L"", opts, &error), "create actual shell");
        if (auto* session = manager.active_session()) {
            auto& host = *session->host;
            check(host.using_conpty(), "test must exercise ConPTY");
            HANDLE process = OpenProcess(SYNCHRONIZE, FALSE, host.pid());
            manager.set_panel_visible(false);
            host.write_utf8("echo SCYLLA_TERMINAL_OK\r");
            bool received = false;
            for (int i = 0; i < 100 && !received; ++i) {
                manager.poll_all();
                wchar_t text[4096]{}; GetWindowTextW(host.hwnd(), text, 4096);
                received = std::wstring(text).find(L"SCYLLA_TERMINAL_OK") != std::wstring::npos;
                Sleep(20);
            }
            check(received, "shell output reaches screen");
            // Exercise the actual HWND key handler, including the duplicate WM_CHAR
            // generated by TranslateMessage for Backspace and Return.
            const std::wstring command = L"if \"abX";
            for (wchar_t c : command) SendMessageW(host.hwnd(), WM_CHAR, c, 1);
            SendMessageW(host.hwnd(), WM_KEYDOWN, VK_BACK, 1);
            SendMessageW(host.hwnd(), WM_CHAR, VK_BACK, 1);
            for (wchar_t c : std::wstring(L"c\"==\"abc\" echo KEY_EDIT_OK")) SendMessageW(host.hwnd(), WM_CHAR, c, 1);
            SendMessageW(host.hwnd(), WM_KEYDOWN, VK_RETURN, 1);
            SendMessageW(host.hwnd(), WM_CHAR, VK_RETURN, 1);
            received = false;
            for (int i = 0; i < 100 && !received; ++i) {
                manager.poll_all();
                wchar_t text[4096]{}; GetWindowTextW(host.hwnd(), text, 4096);
                received = std::wstring(text).find(L"\r\nKEY_EDIT_OK\r\n") != std::wstring::npos;
                Sleep(20);
            }
            check(received, "Backspace edits shell command once and Return submits once");
            host.write_utf8("if \"ac\"==\"abc\" echo ARROW_EDIT_OK");
            SendMessageW(host.hwnd(), WM_KEYDOWN, VK_HOME, 1);
            for (int i = 0; i < 5; ++i) SendMessageW(host.hwnd(), WM_KEYDOWN, VK_RIGHT, 1);
            SendMessageW(host.hwnd(), WM_CHAR, L'b', 1);
            SendMessageW(host.hwnd(), WM_KEYDOWN, VK_RETURN, 1);
            received = false;
            for (int i = 0; i < 100 && !received; ++i) {
                manager.poll_all();
                wchar_t text[4096]{}; GetWindowTextW(host.hwnd(), text, 4096);
                received = std::wstring(text).find(L"\r\nARROW_EDIT_OK\r\n") != std::wstring::npos;
                Sleep(20);
            }
            check(received, "Home and arrows edit in the middle of shell input");
            check((GetWindowLongPtrW(host.hwnd(), GWL_STYLE) & WS_VISIBLE) == 0, "output cannot reshow hidden terminal");
            HWND child = host.hwnd();
            auto start = GetTickCount64();
            manager.close_session_at(0);
            check(GetTickCount64() - start < 2000, "close joins reader promptly");
            check(manager.count() == 0 && !IsWindow(child), "close removes session and child");
            check(process && WaitForSingleObject(process, 1000) == WAIT_OBJECT_0, "close terminates shell");
            if (process) CloseHandle(process);
        } else std::wcerr << error << L'\n';
        DestroyWindow(parent);
    }
    return failures;
}
