<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../scylla-fluent/PreviewText.cs" Link="PreviewText.cs" />
    <Compile Include="../../scylla-fluent/MarkdownLink.cs" Link="MarkdownLink.cs" />
    <Compile Include="../../scylla-fluent/MarkdownImage.cs" Link="MarkdownImage.cs" />
  </ItemGroup>
</Project>
